set nocompatible

source $VIMRUNTIME/mswin.vim
behave mswin

color desert

syntax on

filetype on
filetype indent on
filetype plugin on

set nobackup    " do not keep a backup file, use versions instead

set clipboard+=unnamed	"share system clipboard

if has('mouse')
	set mouse=a
endif

set encoding=utf-8
set fenc=utf-8
set fileencodings=utf-8,cp936,gb2312,gbk,latin1

source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim

"message encoding
language messages zh_CN.utf-8

set history=50		" keep 50 lines of command line history

set incsearch		" do incremental searching
set hlsearch		" highlight search words

set nowrap
set whichwrap+=<,>,h,l

set backspace=2
set textwidth=80

set smartindent
set smarttab
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4

set wildmenu " turn on command line completion wild style
	" ignore these list file extensions
set wildignore=*.dll,*.o,*.obj,*.bak,*.exe,*.pyc,*.jpg,*.gif,*.png
set wildmode=list:longest " turn on wild mode huge list

set autoread

set selection=exclusive
set selectmode=mouse,key
set iskeyword+=_,$,@,%,# " none of these are word dividers 

set cpoptions=aABceFsmq
"             |||||||||
"             ||||||||+-- When joining lines, leave the cursor
"             |||||||      between joined lines
"             |||||||+-- When a new match is created (showmatch)
"             ||||||      pause for .5
"             ||||||+-- Set buffer options when entering the 
"             |||||      buffer
"             |||||+-- :write command updates current file name
"             ||||+-- Automatically add <CR> to the last line 
"             |||      when using :@r
"             |||+-- Searching continues at the end of the match 
"             ||      at the cursor position
"             ||+-- A backslash has no special meaning in mappings
"             |+-- :write updates alternative file name
"             +-- :read updates alternative file name

set linespace=0

set cursorline
hi cursorline guibg=#000000

set number			" always show line number
set numberwidth=5
set scrolloff=5
set ruler			" show the cursor position all the time

set showcmd			" display incomplete commands
set showmode		" always show mode
set showmatch

set laststatus=2	" always show the status line
set statusline=%F%m%r%h%w[%L][%{&ff}]%y[%p%%][%04l,%04v]
"              | | | | |  |   |      |  |     |    |
"              | | | | |  |   |      |  |     |    + current 
"              | | | | |  |   |      |  |     |       column
"              | | | | |  |   |      |  |     +-- current line
"              | | | | |  |   |      |  +-- current % into file
"              | | | | |  |   |      +-- current syntax in 
"              | | | | |  |   |          square brackets
"              | | | | |  |   +-- current fileformat
"              | | | | |  +-- number of lines
"              | | | | +-- preview flag in square brackets
"              | | | +-- help flag in square brackets
"              | | +-- readonly flag in square brackets
"              | +-- rodified flag in square brackets
"              +-- full path to file in the buffer

set guifont=YaHei\ Consolas\ Hybrid:h11

set guioptions=ce 
"              ||
"              |+-- use simple dialogs rather than pop-ups
"              +  use GUI tabs, not console style tabs
set mousehide   "hide mouse when typing
set sessionoptions+=resize


" AutoCmd
if has('autocmd')
    "autocmd GUIEnter * simalt ~x
endif

set guioptions+=m
set guioptions+=T

"KeyMap {
    map <Leader>ee :e $VIM/_vimrc<CR>
    map <Leader>ss :source $VIM/_vimrc<CR>

    nnoremap <space> @=((foldclosed(line('.')) <0) ? 'zc' : 'zo')<CR>

    " set Toolbar, Menu visiable 
	map <Leader>ff :if &guioptions =~# 'T' <Bar>
		\set guioptions-=T <Bar>
		\set guioptions-=m <bar>
		\else <Bar>
		\set guioptions+=T <Bar>
		\set guioptions+=m <Bar>
		\endif<CR><CR>
"}

" PyDiction {
	let g:pydiction_location='$VIM\vimfiles\ftplugin\pydiction\complete-dic'
	let g:pydiction_menu_height = 10
" }

" taglist {
	let Tlist_Show_One_File=1  " only show one file
	let Tlist_Only_Window=1
	let Tlist_Sort_Type = "name" " order by
	let Tlist_Use_Right_Window = 1 " split to the right side of the screen
	let Tlist_Compart_Format = 1 " show small meny
	let Tlist_Exist_OnlyWindow = 1 " if you are the last, kill yourself
	"let Tlist_File_Fold_Auto_Close = 0 " Do not close tags for other files
	"let Tlist_Enable_Fold_Column = 0 " Do not show folding tree
	map <C-w>e <ESC>:TList<CR>
"}

"NERDTree {
	map <C-w>e <ESC>:NERDTreeToggle D:\Project\<CR>:Tlist<CR>
"}


